import { Footer, Navbar } from '@/components';
import type { Metadata } from 'next';
import './globals.css';
import Image from 'next/image';
import vector from './../assets/images/OBJECTS (1).svg'
import vector2 from './../assets/images/OBJECTS (2).svg'
import { montserrat, openSans, roboto } from '@/assets/fonts/fonts';

export const metadata: Metadata = {
  title: 'reclama smart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es" className={`${montserrat.variable} ${openSans.variable} ${roboto.variable}`}>
      <body>
        <Navbar />
        {children}
        <div className='vector2'><Image className='imgVector2' alt='vector2' src={vector2} /></div>
        <div className='vector'><Image className='imgVector' alt='vector' src={vector} /></div>
        <Footer />
      </body>
    </html>
  )
}
