import { Footer, Navbar } from '@/components';
import type { Metadata } from 'next';
import { Roboto, Montserrat, Open_Sans } from 'next/font/google';
import './globals.css';
import Image from 'next/image';
import vector from './../assets/images/OBJECTS (1).svg'
import vector2 from './../assets/images/OBJECTS (2).svg'

const roboto = Roboto({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  variable: '--font-roboto',
  display: 'optional'
});
const montserrat = Montserrat({
  weight: ['400', '500', '700', '900'],
  subsets: ['latin'],
  variable: '--font-montserrat',
  display: 'optional'
});
const openSans = Open_Sans({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  variable: '--font-openSans',
  display: 'optional'
});

export const metadata: Metadata = {
  title: 'reclama smart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={`${montserrat.className} ${openSans.className} ${roboto.className}`}>
        <Navbar />
        {children}
        <div className='vector2'><Image className='imgVector2' alt='vector2' src={vector2} /></div>
        <div className='vector'><Image className='imgVector' alt='vector' src={vector} /></div>
        <Footer />
      </body>
    </html>
  )
}
